In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([2,3,4])
a*b 

array([ 2,  6, 12])

In [3]:
c = np.array([[2.0,3.0,4.0], [4.0,5.0,6.0]])
c

array([[2., 3., 4.],
       [4., 5., 6.]])

In [4]:
#get dimension
a.ndim

1

In [5]:
c.ndim

2

In [6]:
#dimension
a.shape

(3,)

In [7]:
c.shape

(2, 3)

In [8]:
#type
a.dtype

dtype('int32')

In [9]:
#get size
c.itemsize

8

In [10]:
#get totalbytes
b.nbytes

12

In [11]:
c.nbytes

48

In [12]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

In [13]:
to access the value
a[1,4]

SyntaxError: invalid syntax (1887788277.py, line 1)

In [14]:
a[1,-1]

14

In [15]:
#to get the entire row 
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [16]:
#get a specific column
a[:,2]

array([ 3, 10])

In [17]:
#change the value 
a[1,4] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 13, 14]])

In [18]:
a[:,2] = [1,2] 
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 20, 13, 14]])

In [19]:
a[:,2] = [5,5]
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 20, 13, 14]])

In [20]:
#accessing 3d array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
b[0,1,1]

4

In [22]:
b[0,1,1] = 5
b

array([[[1, 2],
        [3, 5]],

       [[5, 6],
        [7, 8]]])

In [23]:
b[:,0,:] = [[9,9],[5,5]]
b

array([[[9, 9],
        [3, 5]],

       [[5, 5],
        [7, 8]]])

In [24]:
#zero matrix
np.zeros((2,3))
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [25]:
#one matrix
np.ones((2,3))
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [26]:
#full matrix 
np.full((4,3,2),2)

array([[[2, 2],
        [2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2],
        [2, 2]]])

In [27]:
#to change the value in the existing matrix
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [28]:
#random decimal numbers
np.random.rand(3,2)

array([[0.5278615 , 0.5390112 ],
       [0.96606828, 0.91858612],
       [0.63246456, 0.43261482]])

In [29]:
#to change the values
np.random.random_sample(a.shape)

array([[0.82766104, 0.09627781, 0.10570475, 0.39183251, 0.92361756,
        0.79273298, 0.58989234],
       [0.81432057, 0.12675078, 0.03482449, 0.28319681, 0.73985686,
        0.1286071 , 0.55980954]])

In [30]:
np.random.randint(5,9, size = (3,3))

array([[7, 6, 8],
       [5, 7, 8],
       [6, 5, 8]])

In [31]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [32]:
#repeat an array
arr = np.array([[[1,2,3]]])
r = np.repeat(arr,3, axis = 0)
r

array([[[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]]])

In [33]:
output = np.ones((5,5))
output
z= np.zeros((3,3))
z[1,1] = 9
output[1:4,1:4] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [34]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
#coping
a = np.array([1,2,3])
b = a.copy()
b

array([1, 2, 3])

In [36]:
#wrong method
a = np.array([1,2,3])
b[1] = 100
a

array([1, 2, 3])

In [37]:
#mathematics

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a + 2

array([3, 4, 5, 6])

In [38]:
a - 2

array([-1,  0,  1,  2])

In [39]:
b ** 2

array([25, 36, 49, 64])

In [40]:
a*b

array([ 5, 12, 21, 32])

In [41]:
b/a

array([5.        , 3.        , 2.33333333, 2.        ])

In [42]:
#take the cos sin value
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [43]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [44]:
a = np.full((2,3),2)
b = np.full((3,2),2)

np.matmul(a,b)

array([[12, 12],
       [12, 12]])

In [45]:
#find the determinant 
c = np.identity(5)
np.linalg.det(c)

1.0

In [46]:
#statistics
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.min(stats)

1

In [48]:
np.max(stats)

6

In [49]:
np.max(stats, axis = 1)

array([3, 6])

In [50]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [51]:
np.sum(stats, axis = 0 )

array([5, 7, 9])

In [52]:
#Reorganizing Arrays
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [53]:
after = before.reshape(4,2)
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [54]:
np.matmul(before,after)

array([[ 50,  60],
       [114, 140]])

In [55]:
#vertically stacking vectors 
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
#horizontal stock
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [57]:
#miscellaneous 
#load data from file 
fileddata = np.genfromtxt(r'C:\Users\DEEPAKRAJ\Downloads\NumPy-master\NumPy-master\data.txt',delimiter = ',')
fileddata
fileddata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [58]:
#boolean masking and advanced masking
fileddata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [59]:
fileddata[fileddata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [60]:
fileddata[fileddata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [61]:
#you can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,-1]]

array([2, 3, 9])

In [62]:
np.any(fileddata > 50, axis = 0) #columns 
np.any(fileddata > 50, axis = 0) #rows


array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [63]:
((fileddata > 50) & (fileddata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [66]:
x = np.random.randn(5)
x
x.shape

(5,)

In [70]:
(x.T)

array([-2.45756668,  0.4013153 , -0.96406393,  0.88613775,  0.35141285])

In [74]:
print(np.dot(x,x.T))

8.03883832441724


In [79]:
b = np.random.randn(5,5) 
b

array([[ 1.68809481, -0.45588486, -0.60604433,  1.4484927 ,  1.67917907],
       [-2.82113098,  0.13109173,  1.72096926,  1.55535072, -0.19324184],
       [ 0.39544988,  0.91734622,  1.49053634, -0.14530317, -0.95030327],
       [-0.66912482, -1.41322671, -1.35768632,  2.3622085 ,  0.17188365],
       [ 1.00909068,  0.64523936, -0.20208765, -0.30107065, -0.05141225]])

In [80]:
print(np.dot(b,b.T))

[[ 8.34255824 -3.93665645 -2.46017839  4.04780581  1.00933095]
 [-3.93665645 13.39415852  1.52744877  3.00673758 -3.56831352]
 [-2.46017839  1.52744877  4.1437926  -4.09128229  0.78233744]
 [ 4.04780581  3.00673758 -4.09128229  9.89782287 -2.03273403]
 [ 1.00933095 -3.56831352  0.78233744 -2.03273403  1.568724  ]]


In [84]:
f=np.random.randn(5,1) #rows
f

array([[-0.03300316],
       [-0.59856833],
       [-0.49226141],
       [-0.5966188 ],
       [ 0.51197541]])